working_directory = "None"

[cursor]
unfocused_hollow = true
vi_mode_style = "block"

[cursor.style]
blinking = "Never"
shape = "Block"

[env]
TERM = "alacritty"

[font]
size = 13.0

[font.normal]
family = "Iosevka"

[scrolling]
multiplier = 6

[shell]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.8
title = "Alacritty"

[window.dimensions]
columns = 20
lines = 20
